baseURL = 'https://dev.codewrite.co.uk/'
locale = 'en-us'
title = 'Codewrite Dev Doc'
theme = 'hugo-book'
pygmentsStyle = "github"

[params]
  BookToC = true
  BookSection = '/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    linenos = true